### ISSUE TITLE
setup.py mentioned in commit message doesn't seem to exist

### ISSUE THREAD

**Issue by mmadsen** [njr0/fish#3]
I'm not seeing a setup.py in the source repository in the latest version, but the commit message for 4.32 suggests one should now exist.....?

**Comment by njr0** [comment]
Hi Mark

Sorry about that: looks like I failed to push the right version to GitHub.   I've just pushed 4.33, which does have it. Let me know if you still have problems, and thanks for letting me know.

Regards

Nick
